---
exclude_paths:
  - '.github/**'
  - 'CHANGELOG.md'
  - '**/CHANGELOG.md'
  - 'changelog/**'
  - '**/changelog/**'
  - 'docs/**'
  - '**/docs/**'
  - '**/pkg/proto/**'
  - 'protogen/**'
  - 'scripts/**'
  - 'idp/ui_config/**'
  - 'idp/scripts/**'
  - 'idp/src/**'
  - 'devtools/**'
  - 'deployments/**'
  - "release-config.ts"
  - 'tests/acceptance/expected-failures-*.md'
  - 'tests/acceptance/bootstrap/**'
  - 'tests/acceptance/TestHelpers/**'
  - 'tests/acceptance/scripts/run.sh'
  - 'vendor/**/*'
  - 'vendor-bin/**'
  - 'tests/ocwrapper/vendor/**'
  - '**/mocks/**'
  - '**/pkg/config/**'
  - '**/pkg/metrics/**'
  - '**/pkg/revaconfig/**'
...
